version: "3"

services: 
postgres:
image: postgres
ports:
 "5432:5432" 
volumes:
-/.docker/laraveldb/postgres:/var/lib/postgressql/data
environment:
POSTGRES_PGDATA: /var/lib/postgressql/data/pgdata
POSTGRES_USER: admin
POSTGRES_DB: laraveldb
POSTGRES_PASSWORD: admin

web:
build:
volumes:
./:/opt/data

ports: 8000:80
depends_on:
postgres
